import Erdos506.V3.PivotGeometry

/-!
# Finite direction API for the twelve-point six-circle branch

This module makes the finite object appearing in the Ungar step explicit.
A direction is the one-dimensional vector subspace spanned by a determined
affine line, i.e. the projective class of the difference of either ordered
pair of points on that line.  The definitions and lemmas here are entirely
unconditional; in particular, this file does **not** postulate Ungar's
theorem or a twelve-point direction inequality.

The remaining geometric step is deliberately visible: the equality case in
the dual off-star count has to produce six noncollinear points whose finite
set `determinedDirections` has cardinality at most five.  Ungar's six-point
theorem then contradicts that witness.  Neither that equality extraction nor
Ungar's theorem is currently available in Mathlib or elsewhere in this
repository.
-/

namespace Erdos506.V1

open Erdos506.Finite
open Erdos506.Incidence
open Erdos506.V3
open Erdos506.V4

/-- The projective direction of two affine points: the line through them is
represented by the submodule generated by their difference.  It is allowed
to be `⊥` for equal points; all uses from a `KSubset _ 2` are distinct. -/
noncomputable def directionOfPoints (x y : Point2) : Submodule ℝ Point2 :=
  ℝ ∙ (y - x)

/-- The direction of an unordered selected pair.  Defining it through the
canonical spanned line keeps the construction independent of an ordering of
the pair. -/
noncomputable def directionOfPair
    {α : Type*} [Fintype α] [DecidableEq α]
    (cfg : Configuration α) (A : KSubset α 2) : Submodule ℝ Point2 :=
  (lineOfPair cfg A).direction

/-- For an ordered presentation of a two-set, `directionOfPair` is exactly
the projective class of the displayed point difference. -/
theorem directionOfPair_eq_directionOfPoints
    {α : Type*} [Fintype α] [DecidableEq α]
    (cfg : Configuration α) {a b : α} (hab : a ≠ b) :
    directionOfPair cfg ⟨{a, b}, by simp [hab]⟩ =
      directionOfPoints (cfg a) (cfg b) := by
  unfold directionOfPair
  rw [lineOfPair_pair cfg hab]
  rw [direction_affineSpan ℝ ({cfg a, cfg b} : Set Point2),
    vectorSpan_pair_rev]
  rfl

/-- The finite set of directions determined by all selected pairs. -/
noncomputable def determinedDirections
    {α : Type*} [Fintype α] [DecidableEq α]
    (cfg : Configuration α) : Finset (Submodule ℝ Point2) := by
  classical
  exact Finset.univ.image (directionOfPair cfg)

/-- Passing from all pairs to projective direction classes cannot increase
the finite census. -/
theorem card_determinedDirections_le_card_pairs
    {α : Type*} [Fintype α] [DecidableEq α]
    (cfg : Configuration α) :
    (determinedDirections cfg).card ≤ Fintype.card (KSubset α 2) := by
  classical
  unfold determinedDirections
  simpa using (Finset.card_image_le :
    (Finset.univ.image (directionOfPair cfg)).card ≤ Finset.univ.card)

/-- Apply an affine equivalence pointwise to a labelled configuration. -/
noncomputable def affineEquivConfiguration
    {α : Type*} (e : Point2 ≃ᵃ[ℝ] Point2)
    (cfg : Configuration α) : Configuration α where
  toFun x := e (cfg x)
  inj' := e.injective.comp cfg.injective

/-- Affine equivalences act injectively on projective direction classes. -/
theorem directionMap_injective_of_affineEquiv
    (e : Point2 ≃ᵃ[ℝ] Point2) :
    Function.Injective
      (fun D : Submodule ℝ Point2 => D.map e.linear.toLinearMap) :=
  Submodule.map_injective_of_injective e.linear.injective

/-- Equality of directions is invariant under an affine equivalence. -/
theorem directionMap_eq_iff_of_affineEquiv
    (e : Point2 ≃ᵃ[ℝ] Point2) (D E : Submodule ℝ Point2) :
    D.map e.linear.toLinearMap = E.map e.linear.toLinearMap ↔ D = E :=
  (directionMap_injective_of_affineEquiv e).eq_iff

/-- The direction of every selected pair is transported by an affine
equivalence using its linear part. -/
theorem directionOfPair_affineEquiv
    {α : Type*} [Fintype α] [DecidableEq α]
    (e : Point2 ≃ᵃ[ℝ] Point2) (cfg : Configuration α) (A : KSubset α 2) :
    directionOfPair (affineEquivConfiguration e cfg) A =
      (directionOfPair cfg A).map e.linear.toLinearMap := by
  have hline :
      lineOfPair (affineEquivConfiguration e cfg) A =
        (lineOfPair cfg A).map e.toAffineMap := by
    simp only [lineOfPair, AffineSubspace.map_span]
    congr 1
    ext x
    simp [affineEquivConfiguration]
  unfold directionOfPair
  rw [hline, AffineSubspace.map_direction]
  rfl

/-- Pointwise affine equivalence transports the entire finite direction
census by the injective map on projective classes. -/
theorem determinedDirections_affineEquiv
    {α : Type*} [Fintype α] [DecidableEq α]
    (e : Point2 ≃ᵃ[ℝ] Point2) (cfg : Configuration α) :
    determinedDirections (affineEquivConfiguration e cfg) =
      (determinedDirections cfg).image
        (fun D => D.map e.linear.toLinearMap) := by
  classical
  unfold determinedDirections
  rw [Finset.image_image]
  apply Finset.image_congr
  intro A _
  exact directionOfPair_affineEquiv e cfg A

/-- Consequently an affine equivalence preserves the number of determined
directions exactly. -/
theorem card_determinedDirections_affineEquiv
    {α : Type*} [Fintype α] [DecidableEq α]
    (e : Point2 ≃ᵃ[ℝ] Point2) (cfg : Configuration α) :
    (determinedDirections (affineEquivConfiguration e cfg)).card =
      (determinedDirections cfg).card := by
  rw [determinedDirections_affineEquiv]
  exact Finset.card_image_of_injective _
    (directionMap_injective_of_affineEquiv e)

/-- A circle through a pivot, viewed after inversion, has the direction of
its corresponding determined line.  Different circles may of course produce
parallel lines, so this is intentionally not an injectivity claim. -/
noncomputable def circlePivotDirection
    {α : Type*} [Fintype α] [DecidableEq α]
    (cfg : Configuration α) (p : α) (c : ↥(circlesThrough cfg p)) :
    Submodule ℝ Point2 :=
  (circleToPivotLine cfg p c).1.direction

/-- The circle-to-line inversion dictionary gives the expected direction for
every two distinct inverted labels on that circle. -/
theorem circlePivotDirection_eq_directionOfPair
    {α : Type*} [Fintype α] [DecidableEq α]
    (cfg : Configuration α) (p : α) (c : ↥(circlesThrough cfg p))
    {q r : AwayFrom p} (hqr : q ≠ r)
    (hq : q.1 ∈ circleTrace cfg c.1.1)
    (hr : r.1 ∈ circleTrace cfg c.1.1) :
    circlePivotDirection cfg p c =
      directionOfPair (pivotInversion cfg p) ⟨{q, r}, by simp [hqr]⟩ := by
  let A : KSubset (AwayFrom p) 2 := ⟨{q, r}, by simp [hqr]⟩
  have hp : p ∈ circleTrace cfg c.1.1 := mem_circlesThrough.mp c.2
  have hmem : ∀ x ∈ A.1,
      pivotInversion cfg p x ∈ circlePivotLine cfg p c.1.1 := by
    intro x hx
    have hxqr : x = q ∨ x = r := by
      simpa [A] using hx
    apply (pivotInversion_mem_circlePivotLine_iff cfg p c.1.1 hp x).2
    rcases hxqr with rfl | rfl
    · exact hq
    · exact hr
  have hline : lineOfPair (pivotInversion cfg p) A =
      circlePivotLine cfg p c.1.1 :=
    lineOfPair_eq_of_mem_of_direction_finrank_one
      (pivotInversion cfg p) A (circlePivotLine cfg p c.1.1) hmem
      (circlePivotLine_direction_finrank cfg p c.1.1 hp)
  change (circlePivotLine cfg p c.1.1).direction =
    (lineOfPair (pivotInversion cfg p) A).direction
  rw [hline]

end Erdos506.V1
